### ISSUE TITLE
myButton.titleLabel.font = [UIFont boldFlatFontOfSize:16];

### ISSUE THREAD

**Issue by gran33** [Grouper/FlatUIKit#113]
Hi,
Awesome UIkit!

The following line raise an error for me (took from the ReadMe file)

myBotton.titleLabel.font = [UIFont boldFlatFontOfSize:16];

The error is some where here:

CTFontManagerRegisterFontsForURL((__bridge CFURLRef)url, kCTFontManagerScopeNone, &error);

Located at:
File: UIFont+FlatUI.m
Line#: 30

Any help/tip will be more then great...

cheers!

**Comment by gclsoft** [comment]
I've the same problem. I add exception breakpoint, and every time it gets exception at CTFontManagerRegisterFontsForURL((__bridge CFURLRef)url, kCTFontManagerScopeNone, &error);
int the UIFont+FlatUI.m.
How to solve it?
