### ISSUE TITLE
Cannot set the correct font for UIBarButtonItem

### ISSUE THREAD

**Issue by pawurb** [Grouper/FlatUIKit#161]
Hello. I have the following problem. I cannot get UIBarButtonItem to look like in the Readme screenshots. I tried using both methods (either setting appearance globally or per controller) but it always looks like this ![image](https://imagizer.imageshack.us/v2/640x168q90/r/913/LcxmfH.png) . 

Any hints on how I can customize the font will be greatly appreciated.

**Comment by johndpope** [comment]
+ (UIBarButtonItem *)newBarButtonItem:(NSString *)iconName pressedIcon:(NSString *)pressedIcon target:(id)target action:(SEL)action {
	const int MaxWidth = 33;
	const int MaxHeight = 27;
    
	// Calculate Button Size
	UIImage *normalImage = [UIImage imageNamed:iconName];
	int width = MIN(normalImage.size.width, MaxWidth);
	int height = MIN(normalImage.size.height, MaxHeight);
    
	// Create Button
	UIButton *button = [[UIButton alloc] initWithFrame:CGRectMake(0, 0, width, height)];
	[button addTarget:target action:action forControlEvents:UIControlEventTouchUpInside];
	[button setBackgroundImage:normalImage forState:UIControlStateNormal];
	[button setBackgroundImage:[UIImage imageNamed:pressedIcon] forState:UIControlStateHighlighted];
    
	// Wrap in BarButtonItem
	return [[UIBarButtonItem alloc] initWithCustomView:button];
}

**Comment by cdbeshore** [comment]
After a little trial and error, adding this to the app delegate worked for me. I think the trick was using appearanceWhenContainedIn and specifying the nav bar class.

[UIBarButtonItem configureFlatButtonsWithColor:[UIColor peterRiverColor]
                                  highlightedColor:[UIColor belizeHoleColor]
                                      cornerRadius:3];
    
[[UIBarButtonItem appearanceWhenContainedIn:[UINavigationBar class], nil]
     setTitleTextAttributes:
     @{NSForegroundColorAttributeName:[UIColor cloudsColor],
       NSFontAttributeName:[UIFont flatFontOfSize:14.0]
       } forState:UIControlStateNormal];
