### ISSUE TITLE
FUIButton in xcode 6.0.1 cannot link to iBaction

### ISSUE THREAD

**Issue by zoelounge** [Grouper/FlatUIKit#163]
I have notice that FUIButton in xcode 6.0.1 cannot link to inaction or iBoutlet.
Someone has the same problem?
Thanks in advance!

**Comment by jamieomatthews** [comment]
Not sure about xcode 6.0.1, but in the newest version 6.1.1, it's working fine.  If you are still having issues, feel free to re-open and describe
