### ISSUE TITLE
FlatUIKit Alternative

### ISSUE THREAD

**Issue by RGSmithSoftware** [Grouper/FlatUIKit#165]
Since FlatUIKit, starting from 1.5, will not be maintained by the creator, I wonder if anybody knows about any alternative?

**Comment by jamieomatthews** [comment]
I will be taking over maintaining FlatUIKit, so no need for an alternative.  I am merging in some new stuff as we speak.  

However, I definitely am interested in any feedback people have about features they'd like to see added.  My first order of business is to try to close out the issues and finish up all the pull requests, but after that I will be looking to create a few more features.
