### ISSUE TITLE
NEW OWNER

### ISSUE THREAD

**Issue by jamieomatthews** [Grouper/FlatUIKit#167]
I'd like to take over maintaining the official fork of FlatUIKit.  My plan is to continue support of iOS6 until there is a good reason to move away from it, but continue to add cool features.  

For example, I added support for using the Flat Icons from [FlatUI](http://designmodo.github.io/Flat-UI/)

You can checkout my fork [here](https://github.com/jamieomatthews/FlatUIKit) . As soon as I have the go-ahead, I will provide documentation in the readme that mine is the "official" fork, and attribute this project as the original.

Thank you for your great work on this project, and cheers to keeping it going.

**Comment by jflinter** [comment]
Boom, I've added you as an admin on the repo. Godspeed.
