### ISSUE TITLE
Cocoapod: NSString+Icons missing in v1.5

### ISSUE THREAD

**Issue by thelastinuit** [Grouper/FlatUIKit#170]
All the classes/ios are installed except for NSString+Icons.

**Comment by jamieomatthews** [comment]
Yep, sorry about that.  From now on I'll be doing work on Develop, and then tagging master when I do a release (and subsequent push to cocoapods).  For now, you can pull manually from master to fix.

@jflinter Can you [add me as a collaborator] (http://guides.cocoapods.org/making/getting-setup-with-trunk.html#adding-other-people-as-contributors)

**Comment by thelastinuit** [comment]
All right, then.
