### ISSUE TITLE
Swift Compatibility? 

### ISSUE THREAD

**Issue by ShayanMahdavi** [Grouper/FlatUIKit#176]
Hi I was wondering if we would be able to use the flatuikit with our swift code. I am currently running into errors when attempting to create say an alertview within a swift file.

**Comment by jamieomatthews** [comment]
It should be possible, I actually haven't tried a project, but I will tonight.  Have you imported objc code into swift before?  If not definitely take a look at the guide [here](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html).  I don't foresee any problems.

**Comment by ShayanMahdavi** [comment]
Yeah I've been able to import objc code into my swift just not with the flatuikit. I get some strange architecture errors when trying to compile say let alertview: FUIAlertView = FUIAlertView()

**Comment by ShayanMahdavi** [comment]
Hi Jamie, I was wondering if you actually were able to get the kit working with swift or what results you found?

**Comment by jamieomatthews** [comment]
@ShayanMahdavi Just setup a test project for this.  (Empty project)

First, made sure I had a [bridging header](http://stackoverflow.com/questions/24102386/swift-bridging-header-h-file-not-allowing-me-to-instantiate-objective-c-classe)

Then, added 
```objc
#import "FlatUIKit.h"
```

to the header. 

Then from swift: 
```objc
let alertView : FUIAlertView = FUIAlertView()
```
compiles fine.  Make sure your minimum target is > iOS6, as flatuikit only supports down to iOS6.

**Comment by ShayanMahdavi** [comment]
Ok yeah I guess it wasn't a swift compatibility issue. Turns out my podfile wasn't configured properly with my project and was the reason we were getting linking errors upon use with the FlatUIKit. I instead just installed the kit manually and that seemed to work as a fix for me.

@jamieomatthews Thanks for looking into the issue with me!

**Comment by jamieomatthews** [comment]
@ShayanMahdavi np

**Comment by y-zono** [comment]
I can use FlatUIKit normally except for FUIAlertView. I got a build error below when I initialize FUIAlertView.

Code

```
FUIAlertView(title: "a", message: "a", delegate: self, cancelButtonTitle: "a", otherButtonTitles: "a")
```

I got build error

```
Extra argument 'otherButtonTitles' in call
```

Any help will be appreciated. I posted my question to [stackoverflow](http://stackoverflow.com/questions/28792107/swift-flatuikit-fuialertview-not-work)

Thanks

**Comment by jamieomatthews** [comment]
Have you tried it like this?  This is a bug with swift interacting with obj c I believe 

```objc
let alert = FUIAlertView()
alert.title = "Title"
alert.message = "Message"
alert.addButtonWithTitle("Ok")
alert.show()
```

**Comment by y-zono** [comment]
@ShayanMahdavi Hi. Thanks for your reply. Yes I have tried that but it did not work. A transparent view was appeared on my viewcontroller but the dialog was not appeared.

**Comment by bardonadam** [comment]
Any chance to resolve issue with not appearing FUIAlertView?

When I defined few properties like this:
    alert.titleLabel.font = UIFont.boldFlatFontOfSize(16)
    alert.messageLabel.textColor = .cloudsColor()
    alert.messageLabel.font = .flatFontOfSize(14)
    alert.backgroundOverlay.backgroundColor = .cloudsColor()
    alert.alertContainer.backgroundColor = .midnightBlueColor()

each line gives error:
fatal error: unexpectedly found nil while unwrapping an Optional value

**Comment by jamieomatthews** [comment]
@bardonadam how is alert defined?

**Comment by bardonadam** [comment]
@jamieomatthews same way as you shown in your [comment](https://github.com/Grouper/FlatUIKit/issues/176#issuecomment-77034721)

**Comment by jamieomatthews** [comment]
@bardonadam that code above worked file for me.  Must be something about accessing title labels, etc that is crashing.  Feel free to open a seperate issue

**Comment by sammygutierrez** [comment]
@y-zono Did you ever figure out a solution to your problem? I'm having the same issue with FUIAlertView.
