### ISSUE TITLE
Can't build in Cocoapods for Ios 8 

### ISSUE THREAD

**Issue by SeanDunford** [Grouper/FlatUIKit#182]
I have FlatUiKit integrated into a cocoapods application and it's throwing the error 
FlatUIKit uses features only available in iOS SDK 5.0 and later.
because of 
FlatUIKit.h Line 12 

#ifndef __IPHONE_5_0
#error "FlatUIKit uses features only available in iOS SDK 5.0 and later."
#endif

Is there any way that you could add support for apps that require a higher minimum sdk version than 5.0?

**Comment by jamieomatthews** [comment]
You mean a lower SDK than 5.0?  We support iOS 6 and later

**Comment by SeanDunford** [comment]
Hmm. Maybe I'm misunderstanding the error. I added FlatUikit via cocoapods to an IOS 8 swift application and it's failing to build with the error 

#error "FlatUIKit uses features only available in iOS SDK 5.0 and later."

I was assuming this was happening because the macro __IPHONE_5_0 is not defined. Is there another way to ensure this macro is set for an ios 8.0 application?

**Comment by jamieomatthews** [comment]
Whats your SDK min on your project? You're building for iOS 8, but whats the min?

**Comment by SeanDunford** [comment]
Minimum sdk  is 8.0. 

When using swift you can't build a minimum sdk lower than 7.0.

**Comment by SeanDunford** [comment]
Would something like this work?
#if __IPHONE_OS_VERSION_MIN_REQUIRED >= __IPHONE_5_0

That way it's an inclusive check for all minimum SDK's 5.0 to latest?

**Comment by SeanDunford** [comment]
Well I just tested it the above will not work. I was misinterpreting what was happening. For some reason the actual macro __IPHONE_5_0 is not defined. So Checking that the os version is higher than an undefined macro wont help anything. 


It seems the underlying cause is that I am referencing FlatUIKit from a bridging header. These __IPHONE_5_0 style preprocessor macros aren't defined at the time the compiler is accessing the bridging header and is throwing the error. Removing FlatUIKit from the bridging header removes the error but does not allow swift interoperability.

**Comment by jamieomatthews** [comment]
Ah ok. What line of code are you putting in your bridging header? I will
try to test it out. I use it with swift all the time, but maybe it's a
swift 1.2 bug or something

**Comment by SeanDunford** [comment]
Both 

#import "FlatUIKit/FlatUIKit.h"
 
and 

#import "FlatUIKit.h"

fail with the same error. I have Pods/** linked in search path and other pod files are working. Swift 1.2 could be the culprit. I imagine it could also be a cocoapods thing as well. I'm using 0.36.4 which is current stable I believe.

**Comment by jamieomatthews** [comment]
I'm taking a look at it now.  It definitely seems to be a new issue.  I'm going to see if I can figure out what people are doing about it, it used to be a pretty common header.  I'm ok with dropping it if I cant find a solution, the only reason its there is to give people a nice verbose error.

**Comment by jamieomatthews** [comment]
Alright, you should be able to run pod update and be all set.  Thanks, let me know if its still an issue.

**Comment by SeanDunford** [comment]
Hey thanks man. I really appreciate how quickly you did that. If I find an alternative check that's available at the bridging header processing I'll submit a pull request.
