### ISSUE TITLE
Get exception at `CTFontManagerRegisterFontsForURL`

### ISSUE THREAD

**Issue by gclsoft** [Grouper/FlatUIKit#184]
I add exception breakpoint, and every time it gets exception at `                CTFontManagerRegisterFontsForURL((__bridge CFURLRef)url, kCTFontManagerScopeNone, &error);`
int the `UIFont+FlatUI.m`.

How to solve it?

**Comment by gclsoft** [comment]
![image](https://cloud.githubusercontent.com/assets/1269898/7477591/68123d8c-f387-11e4-9fa7-14b21e76f5ba.png)

**Comment by gclsoft** [comment]
![image](https://cloud.githubusercontent.com/assets/1269898/7488075/fffaa08e-f3f6-11e4-8470-98e4ed1eaec5.png)

**Comment by jamieomatthews** [comment]
Is this error happening in the example project?  Or in your own project?

**Comment by gclsoft** [comment]
@jamieomatthews Not an error, but catch the exception every time when I debug. In my own project.

**Comment by jamieomatthews** [comment]
Did you copy the fonts over to your project?  I bet this is the problem.  

Verify that you have followed steps 1-4 of this article

http://codewithchris.com/common-mistakes-with-adding-custom-fonts-to-your-ios-app/

**Comment by gclsoft** [comment]
@jamieomatthews Yes. I'm using the pod. I even copy the ttf fonts to my project, it still catch the exception.

**Comment by jamieomatthews** [comment]
You need to do more than copy the ttf into the project.  You need to copy it, make sure its added in the target, and add the font name to the bundle.  Verify that all this is done

**Comment by gclsoft** [comment]
@jamieomatthews I'm not using the pod now and do it as you said, but the same. 
![image](https://cloud.githubusercontent.com/assets/1269898/7507303/753558d6-f4a0-11e4-9cc1-fec4f220735a.png)

**Comment by jamieomatthews** [comment]
Yep, this means that one of the fonts ("Lato-Regular", "Lato-Bold", "Lato-Italic", "Lato-Light"), has not been copied into the project correctly.  This is not a problem with the project, just your configuration.  Please refer to the link I sent that debugs adding a font to an iOS project.

**Comment by gclsoft** [comment]
![image](https://cloud.githubusercontent.com/assets/1269898/7518514/0e6eebe4-f50e-11e4-8d4c-f56454afdf6c.png)
I don't know why, but I failed.

**Comment by jamieomatthews** [comment]
Show me a screen shot of your plist as well, where you added the fonts

**Comment by gclsoft** [comment]
@jamieomatthews  
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>zh_CN</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>com.MyLike.CRM</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.7.20150501</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>UIAppFonts</key>
	<array>
		<string>FontAwesome.ttf</string>
		<string>flat-ui-icons-regular.ttf</string>
		<string>Lato-Bold.ttf</string>
		<string>Lato-Italic.ttf</string>
		<string>Lato-Light.ttf</string>
		<string>Lato-Regular.ttf</string>
	</array>
	<key>UIBackgroundModes</key>
	<array>
		<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>armv7</string>
	</array>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
</dict>
</plist>

```
Even if I removed the ttf in the plist, it still catch the exception.

**Comment by gclsoft** [comment]
Oh, it's because of the `FontAwesome.ttf`!!! Thanks so much! I removed FontAwesome.ttf and everything goes well!

**Comment by jamieomatthews** [comment]
Cool, cheers

**Comment by gclsoft** [comment]
Thanks for your time. I added `FontAwesome.ttf` file to the building setting tab and now OK as well.
