### ISSUE TITLE
FUIAlertView Issue - Swift

### ISSUE THREAD

**Issue by v1n2e7t** [Grouper/FlatUIKit#186]
FUIAlertView crashing in Swift,
This will run:
```swift
let alert = FUIAlertView()
alert.title = "Title"
alert.message = "Message"
alert.addButtonWithTitle("Ok")
alert.show()
```
However nothing is visible

This works:
```swift
let alert = UIAlertView()
alert.title = "Title"
alert.message = "Message"
alert.addButtonWithTitle("Ok")
alert.show()
```
but thats a standard UIAlertView

when i try to add any sort of styling like this:
```swift
let alert = FUIAlertView()
alert.title = "Title"
alert.message = "Message"
alert.addButtonWithTitle("Ok")
alert.backgroundOverlay.backgroundColor = UIColor.cloudsColor().colorWithAlphaComponent(0.8)
alert.show()
```
it crashes with the following error:
``fatal error: unexpectedly found nil while unwrapping an Optional value``

Is there any solution or work around to this?

**Comment by somedev** [comment]
Hey @v1n2e7t
I've made fix for that. Please refer to pull request #187 description
